ALTER TABLE "Setting" 
  ADD COLUMN IF NOT EXISTS "autoDisableEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "autoDisableTime" TEXT NOT NULL DEFAULT '22:00',
  ADD COLUMN IF NOT EXISTS "autoDisableTz" TEXT NOT NULL DEFAULT 'America/Anchorage';
